nishiokadao/freemarket_sample_55b

Gemfile, Gemfile.lock, config/unicorn.rb
gemにUnicorn 追記
ユニコーンのインストールのため
=> add-Unicorn.rb

app/assets/javascripts/slider.js, app/assets/stylesheets/products/_index-header.scss
インデックスのスライド部分のドットボタンの実装
ユーザーの満足度を上げるため
よろしくおねがいします。
=> Add dots button

app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/products/_index-header.html.haml, config/initializers/devise.rb
SNS認証を用いて会員登録を可能にする
ユーザーの会員登録に必要なため
=> Sns authentication

app/assets/stylesheets/_buy.scss, app/assets/stylesheets/application.scss, app/controllers/products_controller.rb, app/views/products/_footer.html.haml, app/views/products/buy.html.haml, config/routes.rb
=> product-buyview(購入確認画面:大田)

app/assets/stylesheets/device/_mypage_side_nav.scss, app/views/device/_mypage_side_nav.html.haml
マイページのサイドバーの部分テンプレート作成
マイページのマークアップの効率をあげる為
=> mypagesideber(マイページサイド：西岡)

app/assets/stylesheets/products/_index-header.scss, app/assets/stylesheets/products/mypage-edit.scss, app/views/products/_index-header.html.haml, app/views/products/mypage-edit.html.haml
=> ユーザー本人確認ページの実装

app/assets/stylesheets/application.scss, app/assets/stylesheets/users/_credit.scss, app/assets/stylesheets/users/_mypage_side_nav.scss, app/assets/stylesheets/users/_profile.scss, app/controllers/users_controller.rb, app/views/users/_mypage_side_nav.html.haml, app/views/users/credit.html.haml, config/routes.rb
クレジットカード登録ページのマークアップ
クレジット登録のため
=> user-creditview(クレジット登録画面：大田)

Gemfile, Gemfile.lock, app/assets/stylesheets/devise/_new.scss, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml
ユーザーの新規登録とログイン機能の実装
サービスを利用する上で必須の機能であるため
=> [WIP] User-registration-and-login(ユーザー新規登録とログイン機能：小林)

db/migrate/20190802101513_addimage_id_to_products.rb, db/migrate/20190803044352_rename_buyer_id_column_to_products.rb, db/schema.rb
productsマイグレーションファイルの修正
db:migration時にエラー発生したため修正
=> マイグレーションファイルの修正：大田

app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, config/routes.rb
SNS認証を使っての新規登録機能の実装
会員登録の選択肢を増やすため
=> User-registration-of-SNS(SNSユーザー新規登録、ログイン：小林)

app/assets/stylesheets/users/_first.scss, app/controllers/application_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users_controller.rb, app/views/devise/registrations/new.html.haml, app/views/products/_index-header-list.html.haml, app/views/products/_index-header.html.haml, app/views/products/index.html.haml, app/views/users/_indexheader.html.haml, app/views/users/_mypage_side_nav.html.haml, app/views/users/show.html.haml, app/views/users/sign_up_fifth.html.haml, app/views/users/sign_up_forth.html.haml, app/views/users/sign_up_second.html.haml, app/views/users/sign_up_third.html.haml, app/views/users/signout.html.haml, config/application.rb, config/locales/devise.ja.yml, config/locales/ja.yml
ビューからのユーザー新規登録の実装、ログイン時サインアウト時のビュー修正。
ビューとサーバーサイドのユーザー新規登録について、ルーティング周りの調整が必要だったため。
=> User sign up（ユーザー新規登録：鈴木）

app/controllers/images_controller.rb, app/controllers/products_controller.rb, app/views/products/_index-container.html.haml, app/views/products/show.html.haml, config/routes.rb
What
商品の詳細表示機能実装。
Why
商品の詳細を確認する為。
=> Item show(商品詳細表示：西岡)

app/controllers/products_controller.rb, app/models/image.rb, app/models/product.rb, app/views/products/_index-container.html.haml, app/views/users/_indexheader.html.haml
=> [WIP]product-list(商品一覧表示：西岡)

app/assets/stylesheets/_users.scss, app/controllers/products_controller.rb, app/models/delivery.rb, app/models/image.rb, app/models/product.rb, app/views/products/_index-container.html.haml, app/views/users/_indexheader.html.haml, config/routes.rb, db/migrate/20190807063147_remove_image_id_from_products.rb, db/migrate/20190807064559_remove_delivery_id_from_products.rb, db/schema.rb
出品した商品を削除する機能の実装
出品できるのに出品した商品を削除できないのはおかしいため
=> FunctionOfDeleteProduct(商品削除機能：小林)

app/assets/stylesheets/products/show.scss, app/controllers/products_controller.rb, app/models/category.rb, app/models/image.rb, app/models/product.rb, app/uploaders/image_uploader.rb, app/views/products/_index-container.html.haml, app/views/products/show.html.haml, config/initializers/carrierwave.rb
出品した商品を一覧表示できるように実装
出品商品の画像を表示させたかったから
=> Product show(商品表示修正：大田)

.gitignore, app/controllers/products_controller.rb
自分の出品した商品を購入できないように実装
自分の商品を購入できるのはおかしいから
=> Product buy varidate(商品購入バリデーション：大田)

app/views/products/new.html.haml, app/views/users/detail.html.haml, app/views/users/profile.html.haml
=> revise..html{class}

app/controllers/products_controller.rb
#What
ログインしていないユーザーが商品一覧・商品詳細以外のページへ行こうとしたらログインページへリダイレクトさせる
#Way
ログアウト時に編集等の操作できない様にする為
https://gyazo.com/69333f510b59ab8bbdbe91f39218df62
=> ログインページへリダイレクト

app/controllers/application_controller.rb, app/controllers/products_controller.rb
＃What  
ログインしていないユーザーが商品一覧・商品詳細以外のページへ行こうとしたらログインページへリダイレクトさせる
＃Way  
ログアウト時に編集等の操作できない様にする為
https://gyazo.com/d4236942d79fc30c2544afd0d91a157b
=> （ログアウト時のアクセス制限：西岡）

app/assets/stylesheets/users/_first.scss, app/controllers/users/sessions_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, app/views/users/sign_up_second.html.haml, app/views/users/sign_up_third.html.haml, config/locales/devise.ja.yml
ユーザー新規登録時のバリデーションについて各項目ごとにエラー文が表示されるように修正。
本家のメルカリの通り、各フォームごとにバリデーションのエラーが出るよう実装
=> User validation（ユーザー新規登録時のバリデーション：鈴木）

app/controllers/products_controller.rb, app/models/product.rb, app/views/products/_index-container.html.haml
トップページにてカテゴリごとに商品を表示するようにした。
本家メルカリのように、カテゴリごとの表示をしたかったため。
=> index-category (トップページにてカテゴリーごとの表示：鈴木)

app/assets/javascripts/modalwindow.js, app/assets/javascripts/slider.js, app/assets/stylesheets/products/_index-container.scss, app/assets/stylesheets/products/_index-footer.scss, app/assets/stylesheets/products/_index-header.scss, app/views/likes/_like.html.haml, app/views/products/_index-header.html.haml
=> adjustment(不具合修正：小林)
